### ISSUE TITLE
Perform a full code review

### ISSUE THREAD

**Issue by Ostrzyciel** [Kaszanas/SC2DatasetPreparator#20]
Review the entire code in the repo. Check and if something is out of order, create tasks to solve it:

- Code formatting standards
- Contribution guides
- Tests – coverage, consistency
- Dependency management

## Found things:
- [x] PRs are by default submitted to main, not dev... review branch protection rules etc. #25
  - [x] PR and issue templates are also not used because they are not in the default branch. #25
- [x] CI doesn't really work. #27 #29
- [x] CLA link is broken. #23
- [x] CLA looks for master, not main. #23
- [x] CLA bot doesn't react to comments – something broken in tokens? #26

**Comment by Kaszanas** [comment]
Yup, I suspect that:

- mkdocs should be working by now 🤔
- code formatting was done with black (I use it everywhere), we may include ruff as a dependency for linting and formatting. 

All of this configuration should be in the pre-commit config.

**Comment by Ostrzyciel** [comment]
Found some issues with the CI – I will stop here, because it's hard for me to work without CI in place, I don't want to break things. Let's focus on resolving what I've found so far.

**Comment by Kaszanas** [comment]
Don't worry about breaking things 😉 we have git for that 💪

**Comment by Ostrzyciel** [comment]
The review is done, I'm closing this. The found issues will be resolved in their respective tasks.
